server:
  port: 9081

spring:
  application:
    name: ray-cloud-app-example-provider
  #zipkin:
  #  base-url: http://admin:admin@localhost:8991
  cloud:
    alibaba:
      seata:
        tx-service-group: raycloud_sample_tx_group
  datasource:
    url: jdbc:mysql://localhost:3306/ray_cloud?useUnicode=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    connectionProperties: config.decrypt=false;
    driver-class-name: com.mysql.jdbc.Driver
    filters: config
    initialSize: 1
    maxActive: 20
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: select 'x'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      registryFetchIntervalSeconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true
