server:
  port: 8889

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#spring:
#  application:
#    name: ray-cloud-config
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: /opt/ray-cloud-config-file

spring:
  application:
    name: ray-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/rayyin/ray-spring-cloud.git
          search-paths: ray-cloud-config/config-properties
          username:
          password: